class Schema extends Object
  Dashboard:
    type: 'Object'
    id:
      type: 'String'
      required: true
      help: "Dashboard Object ID as generated by MongoDB"
    name:
      type: 'String'
      required: true
      help: "Human readable name for the dashboard"
    locked:
      type: 'Boolean'
      required: true
      default: true
      help: "Lock/unlock user's ability to edit the dashboard"
    cols:
      type: 'Int'
      required: true
      default: 1
      help: "How many grid columns the dashboard spans"
    rowHeight:
      type: 'Int'
      required: false
      default: 100
      help: "How many vertical pixels the dashboard spans"
    widgets:
      type: 'Array'
      required: false
      item:
        type: 'Object'
        id:
          type: 'String'
          required: true
          help: "Widget Object ID as generated by MongoDB"
        name:
          type: 'String'
          required: true
          help: "Human readable name for the widget"
        canAlter:
          type: 'Boolean'
          required: true
          default: true
          help: "Allow/disallow user's ability to alter the widget"
        model:
          type: 'String'
          required: false
          default: 'null'
          help: "Backbone model the widget inherits"
        view:
          type: 'String'
          required: true
          help: "Backbone view the widget inherits"
        cols:
          type: 'Int'
          required: true
          default: 1
          help: "How many grid columns the widget spans"
        help: "A widget item"
        extras: false
      help: "A list of widgets that the dashboard contains"
    help: "Dashboard's contain a list of widgets"
    extras: true
  TabContainer:
    type: 'Object'
    id:
      type: 'String'
      required: true
      help: "TabContainer Object ID as generated by MongoDB"
    name:
      type: 'String'
      required: true
      help: "Human readable name for the tab container"
    context:
      type: 'String'
      required: true
      help: "Display rules of the tab container"
    navbar:
      type: 'String'
      required: true
      help: "Navbar element that contains the tab container"
    path:
      type: 'String'
      required: true
      help: "Relative URL path to the tab container"
    tabs:
      type: 'Array'
      required: false
      item:
        type: 'Object'
        model_id:
          type: 'String'
          required: true
          help: "Model Object ID as generated by MongoDB"
        name:
          type: 'String'
          required: true
          help: "Human readable name for the tab"
        view:
          type: 'String'
          required: true
          default: 'dashboard'
          help: "View type of the tab"
        icon:
          type: 'String'
          required: true
          default: '/img/icon-default.png'
          help: "Path to the icon image used in the navbar"
        selected:
          type: 'Boolean'
          required: true
          default: false
          help: "True/false if default selected tab"
        help: "A tab object"
        extras: false
      help: "A list of tabs that the tab container contains"
    help: "Tab container's contain a list of tabs"
    extras: false
  OLAP:
    type: 'Object'
    id:
      type: 'String'
      required: true
      help: "OLAP Object ID as generated by MongoDB"
    name:
      type: 'String'
      required: true
      default: 'All'
      help: "Human readable name for the OLAP"
    olapFilter:
      type: 'Object'
      criteria:
        type: 'Array'
        required: false
        item:
          type:
            type: 'String'
            required: true
            default: 'frame'
          name:
            type: 'String'
            required: false
            default: 'capturetime_epoch'
          exists:
            type: 'Int'
            required: false
            default: 1
          help: "The filter critera"
          extras: true
        help: "A list of criteria for the filtering"
      logic:
        type: 'String'
        required: true
        default: 'and'
      required: false
      help: "OLAP object that describes the OLAP filtering"
      extras: false
    help: "OLAP's contain a filtering object for data retreival"
    extras: false
module.exports = new Schema
